module.exports = function (grunt) {
    'use strict';

    grunt.registerMultiTask('assets_to_sass_variables', 'Creating SASS variables for assets', function () {
        var options = this.options();

        if (!options.hasOwnProperty('assetMapPath') || !options.hasOwnProperty('styleSheetSrc') || !options.hasOwnProperty('filetypes') || !options.hasOwnProperty('sassDestFilename')) {
            grunt.fail.fatal('Asset map, stylesheet src, file type(s) and sass file name must be defined.');
        }

        if (grunt.file.isDir(options.assetMapPath)) {
            grunt.fail.fatal('Asset map not found: ' + options.assetMapPath);
        }

        function getAssetName(assetPath, supportedFileTypes) {
            var filenameRegex = new RegExp('([^/]*?)/?([^/]*).(' + supportedFileTypes.join('|') + ')$'),
                fileInfo = assetPath.match(filenameRegex);

            return (fileInfo !== null && fileInfo.length === 4) ? fileInfo[2] + '-' + fileInfo[3] : false;
        }

        var assetEntries = grunt.file.readJSON(options.assetMapPath),
            sassVariables = [];

        for (var asset in assetEntries) {
            if (assetEntries.hasOwnProperty(asset)) {
                var assetName = getAssetName(asset, options.filetypes);
                if (assetName === false) {
                    continue;
                }

                var fileHashPath = 'static/' + assetEntries[asset],
                    sassVariable = '$' + assetName + ': \'/' + fileHashPath + '\'';

                sassVariables.push(sassVariable);
            }
        }

        var fileContent = [];
        fileContent.push('// This file was automatically generated by Grunt-Task `' + this.name + '`.');
        fileContent.push(sassVariables.join(';\r\n') + ';');

        var fileWasWritten = grunt.file.write(options.styleSheetSrc + options.sassDestFilename, fileContent.join('\r\n'));
        if (fileWasWritten) {
            grunt.log.writeln('Created following variables (in ' + options.styleSheetSrc + options.sassDestFilename + '):\r\n' + sassVariables.join('\r\n'));
        }
    });
};
